### ISSUE TITLE
Link moved

### ISSUE THREAD

**Issue by y2chaits** [skyzyx/php-coding-standards#1]
The link for supporting evidence for conditions (https://www.securecoding.cert.org/confluence/display/seccode/EXP21-C.+Place+constants+on+the+left+of+equality+comparisons) on https://github.com/skyzyx/php-coding-standards/blob/master/GRAMMAR.md

has moved to (https://www.securecoding.cert.org/confluence/display/seccode/VOID+EXP21-C.+Place+constants+on+the+left+of+equality+comparisons)

**Comment by skyzyx** [comment]
Just saw this. Fixed.
